/*
 * Sign Out dan Order Now belum jadi
 */
package pkgfinal.project.attempt.pkg1.views.customer;

import ignoreThis.LoginForm;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import pkgfinal.project.attempt.pkg1.views.AccountView_Login;

/**
 *
 * @author Enrico
 */


public class CustomerView_Interface extends javax.swing.JFrame{

    /**
     * Creates new form CustomerInterfae
     */
    private ArrayList<Integer> currentLocationID;
    private ArrayList<Integer> currentMovieID;

    public ArrayList<Integer> getCurrentLocationID() {
        return currentLocationID;
    }

    public void setCurrentLocationID(ArrayList<Integer> currentLocationID) {
        this.currentLocationID = currentLocationID;
    }

    public ArrayList<Integer> getCurrentMovieID() {
        return currentMovieID;
    }

    public void setCurrentMovieID(ArrayList<Integer> currentMovieID) {
        this.currentMovieID = currentMovieID;
    }

    
    ActionListener updateClockAction = new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            lblClock.setText(new Date().toLocaleString()); 
        }
    };
    
    public CustomerView_Interface(){
        initComponents();
        Timer t = new Timer(1000, updateClockAction);
        t.start();
    }
    
    public void addChooseSeatListener(ActionListener a){
        btnChooseSeat.addActionListener(a);
    }
    
    public void addAddBalanceListener(ActionListener a){
        btnAddBalance.addActionListener(a);
    }
    
    public void addChangeInformationListener(ActionListener a){
        btnChangeInfo.addActionListener(a);
    }
    
    public void addChangePasswordListener(ActionListener a){
        btnChangePass.addActionListener(a);
    }
    
    public void addSignOutListener(ActionListener a){
        menuSignOut.addActionListener(a);
    }
    
    public void addOrderListener(ActionListener a){
        btnOrder.addActionListener(a);
    }
    
    public void addHistoryListener(ActionListener a){
        btnHistory.addActionListener(a);
    }
    
    
    
    public void addLocationListener(ActionListener a){
        locationBox.addActionListener (a);
    }
    public void addMovieListener(ActionListener  a){
        movieBox.addActionListener(a);
    }
    public void addTimeListener(ActionListener  a){
        timeBox.addActionListener(a);
    }
    public void addTheaterListener(ActionListener a){
        cbxTheater.addActionListener(a);
    }
    
    
    public int getSelectedLocation(){
        return locationBox.getSelectedIndex();
    }
    public int getSelectedMovie(){
        return movieBox.getSelectedIndex();
    }
   public String getSelectedTime(){
        return timeBox.getSelectedItem().toString();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        panel1 = new java.awt.Panel();
        AIMenu = new javax.swing.JLayeredPane();
        lblName = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblBalance = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        lblClock = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        movieBox = new javax.swing.JComboBox<>();
        lblMovie = new javax.swing.JLabel();
        lblSeat = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        timeBox = new javax.swing.JComboBox<>();
        lblTime1 = new javax.swing.JLabel();
        locationBox = new javax.swing.JComboBox<>();
        btnOrder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbxTheater = new javax.swing.JComboBox<>();
        btnChooseSeat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        btnAddBalance = new javax.swing.JMenuItem();
        btnHistory = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        btnChangeInfo = new javax.swing.JMenuItem();
        btnChangePass = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuSignOut = new javax.swing.JMenu();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel1.setLayout(new java.awt.BorderLayout());

        AIMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        lblName.setText("Name");

        lblDOB.setText("Birth Date");

        txtName.setEnabled(false);

        txtDOB.setEnabled(false);

        lblEmail.setText("Email");

        txtEmail.setEnabled(false);

        lblBalance.setText("Balance");

        txtBalance.setEnabled(false);

        lblClock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        AIMenu.setLayer(lblName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AIMenu.setLayer(lblDOB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AIMenu.setLayer(txtName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AIMenu.setLayer(txtDOB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AIMenu.setLayer(lblEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AIMenu.setLayer(txtEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AIMenu.setLayer(lblBalance, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AIMenu.setLayer(txtBalance, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AIMenu.setLayer(lblClock, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout AIMenuLayout = new javax.swing.GroupLayout(AIMenu);
        AIMenu.setLayout(AIMenuLayout);
        AIMenuLayout.setHorizontalGroup(
            AIMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AIMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AIMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AIMenuLayout.createSequentialGroup()
                        .addComponent(lblBalance)
                        .addGap(43, 43, 43)
                        .addComponent(txtBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                    .addGroup(AIMenuLayout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addGap(56, 56, 56)
                        .addComponent(txtEmail))
                    .addGroup(AIMenuLayout.createSequentialGroup()
                        .addComponent(lblName)
                        .addGap(54, 54, 54)
                        .addComponent(txtName))
                    .addGroup(AIMenuLayout.createSequentialGroup()
                        .addComponent(lblDOB)
                        .addGap(28, 28, 28)
                        .addComponent(txtDOB, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AIMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        AIMenuLayout.setVerticalGroup(
            AIMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AIMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(AIMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AIMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDOB)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AIMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AIMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBalance)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Order Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        movieBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--" }));

        lblMovie.setText("Movie");

        lblSeat.setText("Seat");

        lblTime.setText("Time");

        timeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--" }));

        lblTime1.setText("Location");

        locationBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--" }));
        locationBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                locationBoxMouseClicked(evt);
            }
        });
        locationBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationBoxActionPerformed(evt);
            }
        });

        btnOrder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnOrder.setText("Order Now !");

        jLabel1.setText("Theater");

        cbxTheater.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--" }));

        btnChooseSeat.setText("Choose Seat");
        btnChooseSeat.setEnabled(false);
        btnChooseSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseSeatActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(movieBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblMovie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblSeat, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblTime, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(timeBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblTime1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(locationBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnOrder, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbxTheater, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnChooseSeat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(lblMovie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(movieBox, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(lblTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(timeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxTheater, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblTime1)
                                .addGap(18, 18, 18)
                                .addComponent(locationBox, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lblSeat)
                                .addGap(46, 46, 46)
                                .addComponent(btnChooseSeat)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime1)
                    .addComponent(locationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMovie)
                    .addComponent(movieBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime)
                    .addComponent(timeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxTheater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeat)
                    .addComponent(btnChooseSeat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setText("Watch Trailer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        menuFile.setText("File");

        btnAddBalance.setText("Add Balance");
        menuFile.add(btnAddBalance);

        btnHistory.setText("History");
        menuFile.add(btnHistory);

        menuBar.add(menuFile);

        menuEdit.setText("Edit");

        btnChangeInfo.setText("Change Email");
        btnChangeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeInfoActionPerformed(evt);
            }
        });
        menuEdit.add(btnChangeInfo);

        btnChangePass.setText("Change Password");
        menuEdit.add(btnChangePass);

        menuBar.add(menuEdit);

        menuHelp.setText("Help");
        menuBar.add(menuHelp);

        menuSignOut.setText("Sign Out");
        menuBar.add(menuSignOut);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AIMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButton1)))
                .addGap(0, 306, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AIMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeInfoActionPerformed
        // TODO add your handling code here:
        System.out.println("action performed");
    }//GEN-LAST:event_btnChangeInfoActionPerformed

    private void locationBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_locationBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_locationBoxMouseClicked

    private void locationBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationBoxActionPerformed

    private void btnChooseSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseSeatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChooseSeatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane AIMenu;
    private javax.swing.JMenuItem btnAddBalance;
    private javax.swing.JMenuItem btnChangeInfo;
    private javax.swing.JMenuItem btnChangePass;
    public javax.swing.JButton btnChooseSeat;
    private javax.swing.JMenuItem btnHistory;
    private javax.swing.JButton btnOrder;
    private javax.swing.JComboBox<String> cbxTheater;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblBalance;
    public javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMovie;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSeat;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTime1;
    private javax.swing.JComboBox<String> locationBox;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuSignOut;
    private javax.swing.JComboBox<String> movieBox;
    private java.awt.Panel panel1;
    private javax.swing.JComboBox<String> timeBox;
    public javax.swing.JTextField txtBalance;
    public javax.swing.JTextField txtDOB;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    public void setLocationComboBoxModel(DefaultComboBoxModel<String> defaultComboBoxModel) {
        this.locationBox.setModel(defaultComboBoxModel);
    }
    public void setMovieComboBoxModel(DefaultComboBoxModel<String> defaultComboBoxModel) {
        this.movieBox.setModel(defaultComboBoxModel);
    }
    public void setTimeComboBoxModel(DefaultComboBoxModel<String> defaultComboBoxModel) {
        this.timeBox.setModel(defaultComboBoxModel);
    }
    public void setTheaterComboBoxModel(DefaultComboBoxModel<String> defaultComboBoxModel) {
        this.cbxTheater.setModel(defaultComboBoxModel);
    }

    public void enableChooseSeat(boolean b) {
        this.btnChooseSeat.setEnabled(b);
    }

    public int getSelectedTheater() {
        return Integer.parseInt(cbxTheater.getSelectedItem().toString());
    }
    public void setPoster(int index) {
        String path = "/pkgfinal/project/attempt/pkg1/resources/buffer" + index+".jpg";
        File someFile = new File("/Users/User/NetBeansProjects/Final Project - Attempt 1/src/pkgfinal/project/attempt/pkg1/resources/buffer"+index+ ".jpg");
        if ((someFile.exists() && !someFile.isDirectory())){
            System.out.println("file found");
            jLabel2.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(path)).getImage().getScaledInstance(270, 400, Image.SCALE_DEFAULT)));
        }else{
            System.out.println("File not found");
        }
    }
    
}