/*
 * Sign Out dan Order Now belum jadi
 */
package pkgfinal.project.attempt.pkg1.views.m;

import ignoreThis.LoginForm;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;
import pkgfinal.project.attempt.pkg1.controller.Customer.CustomerController;
import pkgfinal.project.attempt.pkg1.views.AccountView_Login;

/**
 *
 * @author Enrico
 */


public class CustomerView_Interface extends javax.swing.JFrame{

    /**
     * Creates new form CustomerInterfae
     */
    
    ActionListener updateClockAction = new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            lblClock.setText(new Date().toLocaleString()); 
        }
    };
    
    public CustomerView_Interface(){
        initComponents();
        Timer t = new Timer(1000, updateClockAction);
        t.start();
    }
    
    public void addChooseSeatListener(ActionListener a){
        btnSeat.addActionListener(a);
    }
    
    public void addAddBalanceListener(ActionListener a){
        btnAddBalance.addActionListener(a);
    }
    
    public void addChangeInformationListener(ActionListener a){
        btnChangeInfo.addActionListener(a);
    }
    
    public void addChangePasswordListener(ActionListener a){
        btnChangePass.addActionListener(a);
    }
    
    public void addSignOutListener(ActionListener a){
        menuSignOut.addActionListener(a);
    }
    
    public void addOrderListener(ActionListener a){
        btnOrder.addActionListener(a);
    }
    
    public void addHistoryListener(ActionListener a){
        btnHistory.addActionListener(a);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        panel1 = new java.awt.Panel();
        AIMenu = new javax.swing.JLayeredPane();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtAge1 = new javax.swing.JTextField();
        lblBalance = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhoneNum = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        movieBox = new javax.swing.JComboBox<>();
        lblMovie = new javax.swing.JLabel();
        lblSeat = new javax.swing.JLabel();
        btnSeat = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        timeBox = new javax.swing.JComboBox<>();
        lblTime1 = new javax.swing.JLabel();
        LocationBox = new javax.swing.JComboBox<>();
        btnOrder = new javax.swing.JButton();
        lblClock = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        btnAddBalance = new javax.swing.JMenuItem();
        btnHistory = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        btnChangeInfo = new javax.swing.JMenuItem();
        btnChangePass = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuSignOut = new javax.swing.JMenu();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel1.setLayout(new java.awt.BorderLayout());

        AIMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        lblName.setText("Name");

        lblAge.setText("Age");

        txtName.setEnabled(false);

        txtAge.setEnabled(false);

        lblEmail.setText("Email");

        txtAge1.setEnabled(false);

        lblBalance.setText("Balance");

        txtBalance.setEnabled(false);

        lblPhone.setText("Phone");

        txtPhoneNum.setEnabled(false);

        AIMenu.setLayer(lblName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AIMenu.setLayer(lblAge, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AIMenu.setLayer(txtName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AIMenu.setLayer(txtAge, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AIMenu.setLayer(lblEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AIMenu.setLayer(txtAge1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AIMenu.setLayer(lblBalance, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AIMenu.setLayer(txtBalance, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AIMenu.setLayer(lblPhone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        AIMenu.setLayer(txtPhoneNum, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout AIMenuLayout = new javax.swing.GroupLayout(AIMenu);
        AIMenu.setLayout(AIMenuLayout);
        AIMenuLayout.setHorizontalGroup(
            AIMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AIMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AIMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AIMenuLayout.createSequentialGroup()
                        .addGroup(AIMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblAge)
                            .addComponent(lblEmail))
                        .addGap(28, 28, 28)
                        .addGroup(AIMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAge, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(txtName)
                            .addComponent(txtAge1)))
                    .addGroup(AIMenuLayout.createSequentialGroup()
                        .addGroup(AIMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBalance)
                            .addComponent(lblPhone))
                        .addGap(18, 18, 18)
                        .addGroup(AIMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhoneNum)
                            .addComponent(txtBalance))))
                .addGap(18, 18, 18))
        );
        AIMenuLayout.setVerticalGroup(
            AIMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AIMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AIMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AIMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AIMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtAge1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AIMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBalance)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AIMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Order Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        lblMovie.setText("Movie");

        lblSeat.setText("Seat");

        btnSeat.setText("Choose Seat");

        lblTime.setText("Time");

        lblTime1.setText("Location");

        btnOrder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnOrder.setText("Order Now !");

        jLayeredPane1.setLayer(movieBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblMovie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblSeat, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnSeat, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblTime, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(timeBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblTime1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(LocationBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnOrder, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMovie)
                    .addComponent(lblSeat)
                    .addComponent(lblTime)
                    .addComponent(lblTime1))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSeat)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(timeBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(movieBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LocationBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(404, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMovie)
                    .addComponent(movieBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeat)
                    .addComponent(btnSeat))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime)
                    .addComponent(timeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime1)
                    .addComponent(LocationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblClock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        menuFile.setText("File");

        btnAddBalance.setText("Add Balance");
        menuFile.add(btnAddBalance);

        btnHistory.setText("History");
        menuFile.add(btnHistory);

        menuBar.add(menuFile);

        menuEdit.setText("Edit");

        btnChangeInfo.setText("Change Information");
        menuEdit.add(btnChangeInfo);

        btnChangePass.setText("Change Password");
        menuEdit.add(btnChangePass);

        menuBar.add(menuEdit);

        menuHelp.setText("Help");
        menuBar.add(menuHelp);

        menuSignOut.setText("Sign Out");
        menuBar.add(menuSignOut);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AIMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AIMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane AIMenu;
    private javax.swing.JComboBox<String> LocationBox;
    private javax.swing.JMenuItem btnAddBalance;
    private javax.swing.JMenuItem btnChangeInfo;
    private javax.swing.JMenuItem btnChangePass;
    private javax.swing.JMenuItem btnHistory;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnSeat;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBalance;
    public javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMovie;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblSeat;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTime1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuSignOut;
    private javax.swing.JComboBox<String> movieBox;
    private java.awt.Panel panel1;
    private javax.swing.JComboBox<String> timeBox;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAge1;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNum;
    // End of variables declaration//GEN-END:variables
}